#! /bin/sh
### BEGIN INIT INFO
# Provides:          swupdate-trigger
# Required-Start:    $local_fs
# Should-Start:
# Required-Stop:     $local_fs
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Trigger immediate check for updates, don't wait for polling time
### END INIT INFO

# The definition of actions: (From LSB 3.1.0)
# start         start the service
# stop          stop the service
# restart       stop and restart the service if the service is already running,
#               otherwise start the service
# try-restart   restart the service if the service is already running
# force-reload  cause the configuration to be reloaded if the service supports
#               this, otherwise restart the service if it is running
# status        print the current status of the service

# The start, stop, restart, force-reload, and status actions shall be supported
# by all init scripts; the reload and the try-restart actions are optional

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin

DESC="swupdate-trigger"
NAME="swupdate-trigger"
DAEMON=/usr/bin/swupdate-ipc
PIDFILE=/var/run/$NAME.pid

. /etc/init.d/functions || exit 1

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

#
# Function that starts the daemon/service
#
do_start() {
        local status pid

        status=0
        pid=`pidofproc $NAME` || status=$?
        case $status in
        0)
                echo "$DESC already running ($pid)."
                exit 1
                ;;
        *)
                echo "Starting $DESC ..."
                cd /home/root
                (sleep 5; $DAEMON hawkbitcfg -t) &
                exit 0
                ;;
        esac
}

#
# Function that stops the daemon/service
#
do_stop() {
        # nothing to do for stop
        return 0
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
        (sleep 5; $DAEMON hawkbitcfg -t) &
        return 0
}


#
# Function that shows the daemon/service status
#
status_of_proc () {
        exec $DAEMON gethawkbit
}

case "$1" in
start)
        do_start
        ;;
stop)
        do_stop || exit $?
        ;;
status)
        status_of_proc
        ;;
restart)
        # Always start the service regardless the status of do_stop
        do_stop
        do_start
        ;;
try-restart|force-reload)
        # force-reload is the same as reload or try-restart according
        # to its definition, the reload is not implemented here, so
        # force-reload is the alias of try-restart here, but it should
        # be the alias of reload if reload is implemented.
        #
        # Only start the service when do_stop succeeds
        do_stop && do_start
        ;;
*)
        echo "Usage: $0 {start|stop|status|restart|try-restart|force-reload}" >&2
        exit 3
        ;;
esac
